### ISSUE TITLE
Add support for Ubuntu 16.04 and systemd

### ISSUE THREAD

**Issue by invidian** [whefter/puppet-syncthing#10]
As Ubuntu 16.04 is a new LTS version, this module should probably support it.

**Comment by whefter** [comment]
I can't get Ubuntu 16.04 to either install in VirtualBox (complains about not having a working kernel) or running in Vagrant (crashes with hostname errors).

As such, I can't do any testing in it right now. As for systemd support, I'll have to read up a bit on an easy way to get a basic service script going.

**Comment by mateusz-gozdek-sociomantic** [comment]
[This](https://github.com/syncthing/syncthing/tree/master/etc/linux-systemd) might be useful to solve that.

**Comment by whefter** [comment]
Finally, there are Xenial Vagrant boxes with Puppet >= 4 that work. I can now confirm that the existing init.d script works with Ubuntu 16.04. Additionally, the whole module appears to work with Puppet up to 4.5.x.

I know very little about the Linux init/startup/service managers. The init.d script I provide is based on the one that was part of the btsync module (and GPL, thankfully).

Thanks for the resource. Maybe I'll get around to it over the summer, but if someone really really needs a systemd startup script because the init.d script isn't enough for some reason, they'll have to provide it themselves for the time being - though I'll happily integrate it into the module.
