### ISSUE TITLE
Support all config parameters with validation

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [whefter/puppet-syncthing#12]
That would be nice, if we could specify all config options as parameters, not as one big hash. Additionally, that would allow us to validate parameters to avoid passing not-working config into `syncthing`.

**Comment by whefter** [comment]
The reason I chose this format is because it allows for freestyle config changes when Syncthing parameters change. If we try to re-create all config.xml options as class parameters, we'll be forever busy following every Syncthing release, validating parameters and debugging them.

This way leaves much more freedom to the user. Same goes for validation; I'd expect someone who edits their config.xml to know what they're doing. Adding all sorts of validation (except perhaps for specific, easily misunderstood parameters) will result in a massive work overhead that adds essentially no features.

Thanks, but I don't consider this an issue. I'd consider it more of an issue if the current parameter format didn't allow for absolute full access to the config.xml. Closing this.

**Comment by invidian** [comment]
Thank you for long explanation. I agree about freedom of configuration with current solution and it's good. 

But in my opinion, puppet could and probably should one of the config validation layer. Allowing to specify config options as parameters and validating them is not mutually excluding with freedom of configuration. If `syncthing` change their configuration, end user will be only forced to change their configuration from parameter to custom option. For example [jfryman/nginx](https://github.com/jfryman/puppet-nginx) module allows to both configure something with parameter and also with custom option parameters. And if some kind of advanced user wants to use some not or not-yet supported option, then he should use custom config parameter.

Also, as far as I know, software should be in general as bulletproof as possible, to catch errors as soon as possible, so this would definitely help with this.
